### PR TITLE
Fix file is in use error and access violation error

### PR DESCRIPTION
**Pull request by dotada**
Encountered an access violation error and figured out that ValidData was checking a directory instead of the saveDir file so I fixed that but afterwards it gave me a file is in use error and I figured out it's because File.Create() opens the file and adding a simple Close() fixes it

### CODE REVIEW

**Comment by DaIsimsiz** [comment]
Thanks for pointing this out, since I still haven't tested the app, there may be many more bugs. If I don't forget to do a test today, I will fix all the bugs I can find and *then* add a new release!

**Comment by dotada** [comment]
> Thanks for pointing this out, since I still haven't tested the app, there may be many more bugs. If I don't forget to do a test today, I will fix all the bugs I can find and _then_ add a new release!

No problem! I could really use this tool so I wanted to help as well ;)

**Comment by DaIsimsiz** [comment]
Could you tell me how much experience you have in C#? I am curious!

**Comment by dotada** [comment]
> Could you tell me how much experience you have in C#? I am curious!

I'm now 15, I started around 12 or 13, so a few years split evenly between Windows Forms and Console apps. Combine that with the fact I'm learning C# at school, about 3 years of experience.

**Comment by DaIsimsiz** [comment]
That is wonderful, I happened to start learning at a later age and with a slower pace, so I am not as knowledgeable as I hope I was. Learning programming in a school was also something I wish I could have received, I suggest you to make full use of it, even tho you don't need to hear that from me. Here's a link to the [official AR Discord](https://discord.gg/YRGYFdX) server, we can chat in there if you'd like that!

**Comment by dotada** [comment]
> That is wonderful, I happened to start learning at a later age and with a slower pace, so I am not as knowledgeable as I hope I was. Learning programming in a school was also something I wish I could have received, I suggest you to make full use of it, even tho you don't need to hear that from me. Here's a link to the [official AR Discord](https://discord.gg/YRGYFdX) server, we can chat in there if you'd like that!

fun fact, I'm already in the discord lol, it's how I found out about this tool

**Pull request merged**
